server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workflow_config
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
  output:
    ansi:
      enabled: ALWAYS